from cryptography.fernet import Fernet
import os

def generate_key():
    """
    Generate a new encryption key.
    
    Returns:
        bytes: A URL-safe base64-encoded 32-byte key for Fernet symmetric encryption.
    """
    return Fernet.generate_key()

def encrypt_file(input_path, output_path, key):
    """
    Encrypt the contents of a file using Fernet symmetric encryption.
    
    Args:
        input_path (str): Path to the input file to be encrypted.
        output_path (str): Path where the encrypted file will be saved.
        key (bytes): Encryption key generated by generate_key().
    
    Raises:
        FileNotFoundError: If input file does not exist.
        PermissionError: If there are permission issues reading/writing files.
        ValueError: If key is invalid or empty.
    """
    # Validate inputs
    if not key:
        raise ValueError("Encryption key cannot be empty")
    
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")
    
    try:
        # Create Fernet cipher with the provided key
        fernet = Fernet(key)
        
        # Read input file
        with open(input_path, 'rb') as file:
            file_data = file.read()
        
        # Encrypt the file contents
        encrypted_data = fernet.encrypt(file_data)
        
        # Write encrypted data to output file
        with open(output_path, 'wb') as file:
            file.write(encrypted_data)
    
    except PermissionError:
        raise PermissionError(f"Permission denied when accessing files: {input_path} or {output_path}")
    except Exception as e:
        raise RuntimeError(f"Encryption failed: {str(e)}")